version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestjjjProject
  gitServerName: MyGit
  gitUrl: https://github.com/Gayathri-Saravanan-IBM
  gitUsername: Gayathri-Saravanan-IBM
  gitBranch: main
